### ISSUE TITLE
sso package or sign error

### ISSUE THREAD

**Issue by xiaohao890809** [wenmingvs/WeiBo#10]
请问这个错误怎么解决呢，签名和包名不正确呢？

**Comment by wenmingvs** [comment]
我在自己的环境下没有报这个错误，登录也是正常的。请问你是否是使用测试帐号登录的呢？

**Comment by xiaohao890809** [comment]
是登陆界面进不去

发自我的 iPhone

**Comment by xiaohao890809** [comment]
我是自己新建的项目，是不是包名什么的冲突了呢？

发自我的 iPhone

**Comment by wenmingvs** [comment]
新建项目之后，你还需要很多的工作，才能正确的从服务器中请求回数据

请仔细阅读这个微博第三方API的文档，你需要的资料都在里面

https://github.com/sinaweibosdk/weibo_android_sdk

**Comment by xiaohao890809** [comment]
嗯嗯，谢谢
