### ISSUE TITLE
关于微博应用审核

### ISSUE THREAD

**Issue by MarshallMathersIII** [wenmingvs/WeiBo#14]
作者你好，我是从知乎上看你回答过来，想向你学习一下，开发到“我的”页面，但是新用户接口需要审核成功才可调用，想问下作者是怎样提交审核的，盼回复，谢谢~

**Comment by wenmingvs** [comment]
我是通过调用了已经通过审核的WeiCo客户端中的APP KEY来绕过了审核机制的，很多被关闭的接口如今又可以使用了。

关于新浪微博的授权，参考这个文档，里面有很详细的介绍。https://github.com/qii/weiciyuan/wiki/%E6%96%B0%E6%B5%AA%E5%BE%AE%E5%8D%9A%E6%8E%88%E6%9D%83

如何使用WeiCo的API获取更高级别的接口权限，可以参考我开源项目中的源码，也可以参考这位高中生的开源项目，里面都有具体的用法。https://github.com/PaperAirplane-Dev-Team/BlackLight，
