### ISSUE TITLE
AS2.2.1在mac上构建的时候一直卡住

### ISSUE THREAD

**Issue by huang303513** [wenmingvs/WeiBo#149]
AS2.2.1在mac上构建的时候一直卡住

**Comment by wenmingvs** [comment]
我自己就是在Mac的2.2.1上做构建的，编译通过。

请检查你自己的代理设置是否正常。下载速度太慢会一直卡住


另外尝试替换gradle为你自己本地版本，速度会快很多
![image](https://cloud.githubusercontent.com/assets/10514788/18114897/7f591a70-6f6d-11e6-9c2f-e7c935ae5ec4.png)

**Comment by huang303513** [comment]
谢谢。
