### ISSUE TITLE
刚更新完你的代码，app打开后直接崩溃

### ISSUE THREAD

**Issue by woniu0936** [wenmingvs/WeiBo#15]
错误日志如下：
java.io.FileNotFoundException: /storage/emulated/0/weiSwift/home/全部微博2133922964.txt: open failed: ENOENT (No such file or directory)
06-08 11:19:48.585 11813-11813/com.wenming.weiswift W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:496)
06-08 11:19:48.585 11813-11813/com.wenming.weiswift W/System.err:     at java.io.FileInputStream.<init>(FileInputStream.java:76)
06-08 11:19:48.585 11813-11813/com.wenming.weiswift W/System.err:     at java.io.FileReader.<init>(FileReader.java:42)
06-08 11:19:48.585 11813-11813/com.wenming.weiswift W/System.err:     at com.wenming.weiswift.utils.SDCardUtil.get(SDCardUtil.java:114)
06-08 11:19:48.585 11813-11813/com.wenming.weiswift W/System.err:     at com.wenming.weiswift.mvp.model.imp.StatusListModelImp.cacheLoad(StatusListModelImp.java:139)
06-08 11:19:48.586 11813-11813/com.wenming.weiswift W/System.err:     at com.wenming.weiswift.mvp.presenter.imp.HomeFragmentPresentImp.firstLoadData(HomeFragmentPresentImp.java:79)
06-08 11:19:48.586 11813-11813/com.wenming.weiswift W/System.err:     at com.wenming.weiswift.ui.login.fragment.home.HomeFragment$1.run(HomeFragment.java:95)
06-08 11:19:48.586 11813-11813/com.wenming.weiswift W/System.err:     at android.os.Handler.handleCallback(Handler.java:815)
06-08 11:19:48.586 11813-11813/com.wenming.weiswift W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:104)
06-08 11:19:48.586 11813-11813/com.wenming.weiswift W/System.err:     at android.os.Looper.loop(Looper.java:192)
06-08 11:19:48.586 11813-11813/com.wenming.weiswift W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5784)
06-08 11:19:48.586 11813-11813/com.wenming.weiswift W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
06-08 11:19:48.586 11813-11813/com.wenming.weiswift W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
06-08 11:19:48.586 11813-11813/com.wenming.weiswift W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1084)
06-08 11:19:48.586 11813-11813/com.wenming.weiswift W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:850)
06-08 11:19:48.586 11813-11813/com.wenming.weiswift W/System.err: Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
06-08 11:19:48.586 11813-11813/com.wenming.weiswift W/System.err:     at libcore.io.Posix.open(Native Method)
06-08 11:19:48.586 11813-11813/com.wenming.weiswift W/System.err:     at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
06-08 11:19:48.586 11813-11813/com.wenming.weiswift W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:482)
06-08 11:19:48.586 11813-11813/com.wenming.weiswift W/System.err: 	... 14 more
06-08 11:19:48.587 11813-11813/com.wenming.weiswift D/AndroidRuntime: Shutting down VM
06-08 11:19:48.587 11813-11813/com.wenming.weiswift W/System.err: java.lang.NullPointerException: Attempt to invoke interface method 'void com.wenming.weiswift.mvp.model.StatusListModel$OnDataFinishedListener.noDataInFirstLoad(java.lang.String)' on a null object reference
06-08 11:19:48.587 11813-11813/com.wenming.weiswift W/System.err:     at com.wenming.weiswift.mvp.model.imp.StatusListModelImp.cacheLoad(StatusListModelImp.java:149)
06-08 11:19:48.587 11813-11813/com.wenming.weiswift W/System.err:     at com.wenming.weiswift.mvp.presenter.imp.HomeFragmentPresentImp.firstLoadData(HomeFragmentPresentImp.java:79)
06-08 11:19:48.587 11813-11813/com.wenming.weiswift W/System.err:     at com.wenming.weiswift.ui.login.fragment.home.HomeFragment$1.run(HomeFragment.java:95)
06-08 11:19:48.587 11813-11813/com.wenming.weiswift W/System.err:     at android.os.Handler.handleCallback(Handler.java:815)
06-08 11:19:48.587 11813-11813/com.wenming.weiswift W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:104)
06-08 11:19:48.587 11813-11813/com.wenming.weiswift W/System.err:     at android.os.Looper.loop(Looper.java:192)
06-08 11:19:48.587 11813-11813/com.wenming.weiswift W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5784)
06-08 11:19:48.587 11813-11813/com.wenming.weiswift W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
06-08 11:19:48.587 11813-11813/com.wenming.weiswift W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
06-08 11:19:48.587 11813-11813/com.wenming.weiswift W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1084)
06-08 11:19:48.587 11813-11813/com.wenming.weiswift W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:850)
06-08 11:19:48.588 11813-11813/com.wenming.weiswift E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: com.wenming.weiswift, PID: 11813
                                                                      java.lang.NullPointerException: Attempt to invoke interface method 'void com.wenming.weiswift.mvp.model.StatusListModel$OnDataFinishedListener.noDataInFirstLoad(java.lang.String)' on a null object reference
                                                                          at com.wenming.weiswift.mvp.model.imp.StatusListModelImp.cacheLoad(StatusListModelImp.java:149)
                                                                          at com.wenming.weiswift.mvp.presenter.imp.HomeFragmentPresentImp.firstLoadData(HomeFragmentPresentImp.java:79)
                                                                          at com.wenming.weiswift.ui.login.fragment.home.HomeFragment$1.run(HomeFragment.java:95)
                                                                          at android.os.Handler.handleCallback(Handler.java:815)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                          at android.os.Looper.loop(Looper.java:192)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5784)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:372)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1084)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:850)

**Comment by wenmingvs** [comment]
本地存储路径，有个叫做weiswift的文件夹，整个删除掉，再打开app试下。我今天会修复一下这个bug。感谢你的提醒

**Comment by wenmingvs** [comment]
本地存储路径，有个叫做weiSwift的文件夹，整个删除掉，再打开app试下。我今天会修复一下这个bug。感谢你的提醒

**Comment by wenmingvs** [comment]
本地存储路径，有个叫做weiSwift的文件夹，整个删除掉，再打开app试下。我今天会修复一下这个bug。感谢你的提醒

**Comment by wenmingvs** [comment]
请更新一下代码，我已经修复了这个Bug，感谢你的issue
