### ISSUE TITLE
不敢说是问题

### ISSUE THREAD

**Issue by wangchang163** [wenmingvs/WeiBo#159]
底部导航出现两个发现，最后应该是我的页面

**Comment by wenmingvs** [comment]
有相关的图片发上来吗？我确认下问题

**Comment by wangchang163** [comment]
![qq 20160912162135](https://cloud.githubusercontent.com/assets/12017058/18429213/e4ac7106-7904-11e6-83b8-500146713017.png)

**Comment by wenmingvs** [comment]
感谢，我已经纠正这个问题
