### ISSUE TITLE
大神请问头条文章那个怎么实现啊？急～

### ISSUE THREAD

**Issue by AdleyLong** [wenmingvs/WeiBo#16]

**Comment by AdleyLong** [comment]
能不能提供点思路

**Comment by wenmingvs** [comment]
能否具体说下是头条文章的哪一块？是时间线上显示头条文章的标签栏，还是头条文章的浏览界面？

**Comment by AdleyLong** [comment]
是头条文章的编辑，我自己实现了下，用户体验有点不好

**Comment by wenmingvs** [comment]
抱歉，新浪微博并没有提供发布头条文章的接口，所以我并没有做的打算。

我粗略的看了一下，并不是很难，动态添加子view到ViewGroup这个容器里面就好了。建议加深对于自定义ViewGroup的了解，网上有不少教程。另外里面涉及大量的EditTextView，要善用ScrollView来阻止EditText每次下拉重复获取焦点，不然用户体验非常差

**Comment by AdleyLong** [comment]
差不多，我是用了个recyclerview，然后往里面添加子项，但是edittext按回车的时候，光标没有移下去，删除一行edittext的时候，光标也没有上去，不知道这块能否指导下？

**Comment by wenmingvs** [comment]
能发源码我看看吗？我下班了帮你看看。

**Comment by AdleyLong** [comment]
项目代码太多了，我发几个关于这个功能的java问你吧？能告诉下邮箱地址吗

**Comment by wenmingvs** [comment]
你可以简单的抽一个简单的Demo出来给我就好了。如果没有具体的代码，我很难做调试，只能靠猜。我的邮箱是wenmingvs@foxmail.com

**Comment by wenmingvs** [comment]
最近工作太忙，后面我抽个时间帮你看看。我暂时把这个issue关掉，因为你的issue和这个项目没关系了
