### ISSUE TITLE
我要口吐白沫啦

### ISSUE THREAD

**Issue by ananas-xxj** [wenmingvs/WeiBo#164]
实在是无法看懂

**Comment by wenmingvs** [comment]
https://github.com/wenmingvs/WeiBo/issues/38

你好，我对我自己的代码可读性还是很有信心的，网友阅读起来也没有问题的。可能你需要对MVP模式进一步了解，才会有更深的理解。

**Comment by ananas-xxj** [comment]
我对此模式初次了解, 有些难理解. 我想为我的年少无知,提出道歉,对不起! 感谢你的分享与包容!
