### ISSUE TITLE
有个bug

### ISSUE THREAD

**Issue by kebenxiaoming** [wenmingvs/WeiBo#170]
在WeiBo/weiboSDK/src/main/java/com/sina/weibo/sdk/openapi/models/Visible.java文件中的last_id字段获取值的时候有超过int最大值的情况，所以需要改为long类型

**Comment by kebenxiaoming** [comment]
呃呃呃，这东西功能有点少啊

**Comment by wenmingvs** [comment]
我微博中，并没有真正用到VIsible类中的属性和方法，因为我观察服务器返回的Visible字段的属性，type字段和last_id字段永远都是0，并不会出现你说的情况

不过还是非常感谢你的提醒。希望下次提的Bug能更加有价值，谢谢

**Comment by kebenxiaoming** [comment]
我就碰到了，我的微博返回的last_id不是0啊，而且大于int最大值，程序会崩溃
@wenmingvs

**Comment by wenmingvs** [comment]
能把服务器返回的json数据贴上来吗？

**Comment by kebenxiaoming** [comment]
你自己试试点击关注列表的用户详情吧
@wenmingvs 估计可以看到
