### ISSUE TITLE
打搅了，关于长图显示的问题

### ISSUE THREAD

**Issue by VainAnts** [wenmingvs/WeiBo#174]
从这个https://pvg.v2ex.com/t/279359        看过来的，你加载长图用的那个框架，我用Glide应该怎么操作啊，我现在用的是PhotoView

**Comment by wenmingvs** [comment]
你好，我对于Glide的了解并不比你多，所以没有办法解决你的困惑。但是我觉得这个问题还是蛮基本的，Glide肯定也像ImageLoader一样，提供了通过url获取缓存图片File的接口。另外我也不建议再使用PhotoView加载长图，原因我已经在帖子里面说了。
