### ISSUE TITLE
微博详情页转发评论悬浮

### ISSUE THREAD

**Issue by zaaach** [wenmingvs/WeiBo#176]
微博详情页滑动到转发评论那一栏，继续滑动会悬浮在那里，可以实现这个吗

**Comment by 50kg** [comment]
同求用户信息页tabalyout悬浮，求思路

**Comment by wenmingvs** [comment]
可以去GitHub中的寻找Recyclerview的粘性控件，参考这个https://github.com/emilsjolander/StickyListHeaders
