### ISSUE TITLE
大神怎么不继续维护这个项目了？

### ISSUE THREAD

**Issue by jayleco** [wenmingvs/WeiBo#178]
看了这个项目学到好多知识点，老大怎么不继续维护了啊？

**Comment by wenmingvs** [comment]
工作之后时间太少了，每天到家已经9点多了，累，后面抽时间维护吧

**Comment by jayleco** [comment]
发现您这个项目在长图浏览的时候左右翻页偶尔会出现闪退现象，测试机型华为荣耀4x
