### ISSUE TITLE
关于下拉刷新与上拉加载更多

### ISSUE THREAD

**Issue by adustdu2015** [wenmingvs/WeiBo#179]
大神，我自己怎么在recyclerview中写下拉刷新和上拉加载更多呢？给个指导吧，谢谢！

**Comment by wenmingvs** [comment]
谷歌上已经有很多解决方案了，你可以搜索一下。我觉得至少百度一下再提问吧，这是发问的礼仪，也是对别人的最基本的尊重。

发自我的 iPhone
