### ISSUE TITLE
大神，关于recyclerview置顶以及取消置顶有没有好的方案，百度谷歌找遍了，自己实现的时候问题颇多

### ISSUE THREAD

**Issue by leejay001** [wenmingvs/WeiBo#180]
for(int i=position;i>0;i--){
            Collections.swap(mList,i,i-1);
        }
 notifyItemMoved(position,0); 
notifyDataSetChanged(); 
这是置顶的时候调用的两个方法，上面的for是为了一个一个交换位置，要不然就是互换，不是置顶了
问题在于，置顶的元素我会设置一个标志，只有有这个标志的背景颜色才变，但是实际发现，没有这个标志的背景颜色也发生了变化。而且上下滑动几次，有的item还会出现背景颜色的变化，望回复

**Comment by liwenwei** [comment]
最后你置顶的解决方案是？

**Comment by liwenwei** [comment]
我这用的SortedList，置顶和取消置顶后排序的list没问题，就是在更新UI时，老是出问题，麻烦告之一下你的解决方案
