### ISSUE TITLE
recyclerview图片错乱

### ISSUE THREAD

**Issue by cyq7on** [wenmingvs/WeiBo#2]
lz，我最近也在做类似的东西，我已经把图片加载的框架都跟你用一样的了，然而还是会出现图片错乱的现象，难道是你的WeiboAdapter里调用了requestLayout？？

**Comment by wenmingvs** [comment]
我在开发微博的时候，也遇到这个问题。最后确定问题是由于RecyclerView复用ViewHolder引起的，
RecyclerView内部会自动判断ViewHolder是否需要重新刷新来加载新的数据，这套判断的逻辑有时候遇到一些复杂的item布局的时候，就会出现问题，导致一些有图的微博item复用了之前无图的微博item的ViewHolder，图片也就显示不出来了

解决办法：让RecyclerView认为这个ViewHolder需要重新刷新来加载新的数据

在设置图片前，手动调用

  (Viewholder).recyclerview.setVisibility(View.GONE);
   (Viewholder).recyclerview.setVisibility(View.VISIBLE);


这样图片就不会出现乱序问题了

**Comment by wenmingvs** [comment]
你好，我已经在GitHub上回复你的issue，你可以尝试一下使用我的思路，如果成功请在Github留言告诉我哦



wenmingvs@gmail.com
 
发件人： cyq7on
发送时间： 2016-01-14 17:55
收件人： wenmingvs/WeiBo
主题： [WeiBo] recyclerview图片错乱 (#2)
lz，我最近也在做类似的东西，我已经把图片加载的框架都跟你用一样的了，然而还是会出现图片错乱的现象，难道是你的WeiboAdapter里调用了requestLayout？？

**Comment by cyq7on** [comment]
这两句我加上了的，然而还是会乱，好忧桑。。。

**Comment by wenmingvs** [comment]
使用ImageLoader是否有使用占位图？
尝试使用下面这句

  options = new DisplayImageOptions.Builder()
                .showImageOnLoading(R.drawable.message_image_default)
                .showImageForEmptyUri(R.drawable.message_image_default)
                .showImageOnFail(R.drawable.message_image_default)
                .cacheInMemory(true)
                .cacheOnDisk(true)
                .considerExifParams(true)
                .build();


图片可以自己设置

**Comment by cyq7on** [comment]
嗯，这些当然都设置了

**Comment by wenmingvs** [comment]
写下你的开源项目的地址，我帮你看一下

**Comment by cyq7on** [comment]
lz，我发你的源码你收到了吗

**Comment by wenmingvs** [comment]
没有收到，请发到wenmingvs@foxmail.com

**Comment by joetang1989** [comment]
可参考Android-Universal-Image-Loader中机制，将ImageView的hashcode作为key，图片url作为value，存储线程安全的hashmap中。下载后display时，根据ImageView的hashcode从hasmap中取图片url，如果被复用了，那么取出来的url与图片的url不一致，不需要显示。
