### ISSUE TITLE
请问下HeaderAndFooterRecyclerView应用于多列列表刷新时底部footer异常,有什么好的解决办法吗?

### ISSUE THREAD

**Issue by 523931340** [wenmingvs/WeiBo#28]
比如:微博 我的 - 我的相册的加载更多时脚布局异常

**Comment by wenmingvs** [comment]
你说的底部footer异常，是指这个吗？https://github.com/cundong/HeaderAndFooterRecyclerView/issues/15

**Comment by 523931340** [comment]
当使用RecyclerView加载多列数据时 实现像GridView的效果,加载更多时脚布局会乱掉 [不会出现在RecyclerView的最底部(如图所示)
![screenshot_2016-07-16-16-32-33-689_com wenming we](https://cloud.githubusercontent.com/assets/13196209/16893826/567d9894-4b76-11e6-8ff1-188192fdf02f.jpg)

**Comment by wenmingvs** [comment]
主要原因是服务器返回给我的图片的URL并不是3的倍数，导致我footer出了问题，我在做这个需求的时候太赶，这个细节我就暂时忽略了。

解决办法是对服务器返回url的数量做一下检查，不满3倍就自动使用空白的URL做补全。这样就能保证图片至少能沾满屏幕了。然后footerView的布局也要重新做调整，让字体居中，另外通过以下代码，让footerView占满3格，这样footerView就能正常的显示了，关键代码如下：

``` java
GridLayoutManager gridLayoutManager = new GridLayoutManager(mContext, 3, GridLayoutManager.VERTICAL, false);
            gridLayoutManager.setSpanSizeLookup(new GridLayoutManager.SpanSizeLookup() {
                @Override
                public int getSpanSize(int position) {
                    //footerview
                    if (position == mData.size()) {
                        return 3;
                    }
                    return 1;
                }
            });
```

**Comment by 523931340** [comment]
恩,大概了解了,谢谢
