### ISSUE TITLE
Error: 10006 and 21332

### ISSUE THREAD

**Issue by rexcheung** [wenmingvs/WeiBo#3]
已经成功授权，但重启App后Toast提示错误信息，先是10006，然后是21332

**Comment by wenmingvs** [comment]
你好，您需要在设置里面注销了再重新登录授权。对于第三方的客户端，token有效期只有7天，过期只能重新授权。这个也是让我们这些开发者非常蛋疼的地方，给你带来的不便请谅解

**Comment by rexcheung** [comment]
其实我是刚刚编译完，安装上后授权，就出现此问题，晚上再试下注销掉。

**Comment by wenmingvs** [comment]
我昨天也测试了一下我的手机，也遇到了这个问题，不过注销就解决了，非常感谢你的提醒，这个bug很隐晦



wenmingvs@gmail.com
 
From: zxb
Date: 2016-01-26 10:54
To: wenmingvs/WeiBo
CC: wenmingvs
Subject: Re: [WeiBo] Error: 10006 and 21332 (#3)
其实我是刚刚编译完，安装上后授权，就出现此问题，晚上再试下注销掉。

**Comment by rexcheung** [comment]
注销之后的确可以了。
