### ISSUE TITLE
您好，想请教您关于这个APP设计上的问题

### ISSUE THREAD

**Issue by yuruxuan** [wenmingvs/WeiBo#39]
1.我看您的layout文件拆分的特别碎，比如说一个TitleBar就整了一个xml文件，为什么要拆这么碎啊
2.一般在公司里写代码是按照功能模块划分么（首页，消息。。。），我一般都是按照代码功能划分（Activity，Fragment。。）
3.Mvp会造成类爆炸，但是我见代码中注释到是为了解决Fragment过于复杂才这么设计的，为什么？

**Comment by wenmingvs** [comment]
1. 其实最初的版本，我就是多个TitleBar对应一个XML文件的，不同的Fragment使用一个XML文件，然后在相应的fragment中用代码对TitleBar里面的TextView做文本调整。但是到后面，TitleBar的功能就不这么简单了，比如首页的TitleBar就有个小箭头图标，发现页的TitleBar是一个搜索栏等等，这样，我还需要在代码里面做各种隐藏和显示操作，这样会让代码非常混乱，也很难后期维护。所以我打算每个fragment对应的TtileBar，如果后期TitleBar需要增加新的功能样式，我也可以方便扩展。

2. 为什么采用MVP，如果你自己负责过一个非常完整的App项目，我想你就能明白架构对于程序设计的重要性。我最初设计的版本并没有使用MVP，导致了在fragment中不仅仅需要做更新各种UI部件，还需要做数据的网络请求，请求回来的数据我还要进行相应的二重处理等等。不仅仅在这个fragment中我需要做这些操作，我还需要在别的fragment中也需要重复做这些操作，这样代码就会冗余，而且会难以后期维护，我有一段时间写到后面完全不想再写，觉得非常烦，后来下定决定重构全部代码，才有写下去的动力。

你提到类爆炸这个点，我觉得其实还好，并没有到爆炸那么恐怖，只是把若干的功能都分离成更小的单元而已，MVP导致类的增多，其实大部分是接口类的增多，通过继承接口，我们后期做各种扩展，而不会影响到之前的代码方案，这也是MVP的好处。这也符合『对修改封闭，对扩展开发』的设计原则。

希望我的回答能解决你的困惑！
