### ISSUE TITLE
你好，我在你的基础上增加了话题和用户背景点击效果，你可以参考一些

### ISSUE THREAD

**Issue by ckenergy** [wenmingvs/WeiBo#84]
[DEMO](https://github.com/ckenergy/TextViewClickDemo) 
![](https://github.com/ckenergy/TextViewClickDemo/blob/master/img/2.gif)

**Comment by wenmingvs** [comment]
我之前在做TextView的关键词高亮的时候，也实现了和你这个效果，但是运用在项目里面却没有点击高亮的效果，我猜想是主题设置的问题，所以暂时不改了。而且这个效果并不是我想要的，应该和新浪微博一样，按住才会变色，松开就还原回去，但是你这个好像不行？你不妨fork我的源码，在上面做改动，再给我看效果如何？如果OK而且没有bug，我可以合进来
